# Generated by Django 5.2 on 2025-06-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_app', '0004_sharepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharePost',
        ),
    ]
