# Generated by Django 5.2 on 2025-06-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_userprofile_user_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
