# Generated by Django 5.2 on 2025-06-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_userprofile_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default="This user hasn't added a bio yet."),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/defaultimg.jpg', upload_to='profile_images/'),
        ),
    ]
