# Generated by Django 5.2 on 2025-07-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_userprofile_bio_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.URLField(default='https://res.cloudinary.com/dq8biwq8q/image/upload/v1751619038/defaultimg_nfiht1.jpg'),
        ),
    ]
