# Generated by Django 5.2 on 2025-06-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0003_message_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_post_share',
            field=models.BooleanField(default=False),
        ),
    ]
