# Generated by Django 5.2 on 2025-06-12 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0004_message_is_post_share'),
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='shared_post_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='shared_post_media',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='shared_post_media_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post_app.post'),
        ),
    ]
